DE_INGREDIENT_NAMES = {
    "00 flour or bread flour": "00-Mehl oder Brotmehl",
    "achiote paste": "Achiote-Paste",
    "active dry yeast": "Trockenhefe",
    "all-purpose flour": "Weizenmehl (Type 405)",
    "baking powder": "Backpulver",
    "baking soda": "Natron",
    "bean sprouts": "Sojasprossen",
    "beef sirloin": "Rinderhüfte",
    "bell pepper": "Paprika",
    "bell peppers": "Paprika",
    "black pepper": "schwarzer Pfeffer",
    "black vinegar": "schwarzer Essig",
    "boneless chicken thighs": "Hähnchenoberschenkel, ohne Knochen",
    "burger buns": "Burgerbrötchen",
    "butter": "Butter",
    "buttermilk": "Buttermilch",
    "canned chickpeas": "Kichererbsen aus der Dose",
    "canned san marzano tomatoes": "San-Marzano-Tomaten aus der Dose",
    "carrot": "Karotte",
    "cauliflower": "Blumenkohl",
    "chana masala spice blend": "Chana-Masala-Gewürzmischung",
    "cheddar cheese slices": "Cheddar-Käsescheiben",
    "chicken breast": "Hähnchenbrust",
    "chicken thighs": "Hähnchenschenkel",
    "cilantro": "Koriandergrün",
    "coconut milk": "Kokosmilch",
    "cooked short-grain rice": "gekochter Rundkornreis",
    "coriander powder": "Korianderpulver",
    "corn tortillas": "Maistortillas",
    "cornstarch": "Speisestärke",
    "cucumber": "Gurke",
    "cumin powder": "Kreuzkümmelpulver",
    "cumin seeds": "Kreuzkümmelsamen",
    "dashi stock": "Dashi-Brühe",
    "dried chickpeas": "getrocknete Kichererbsen",
    "dried oregano": "getrockneter Oregano",
    "dried red chilies": "getrocknete rote Chilis",
    "dried wakame seaweed": "getrocknete Wakame-Algen",
    "eggplant": "Aubergine",
    "eggs": "Eier",
    "extra virgin olive oil": "natives Olivenöl extra",
    "feta cheese block": "Feta-Käse",
    "fish sauce": "Fischsauce",
    "fresh basil leaves": "frische Basilikumblätter",
    "fresh mozzarella": "frischer Mozzarella",
    "garam masala": "Garam Masala",
    "garlic": "Knoblauch",
    "garlic clove": "Knoblauchzehe",
    "garlic cloves": "Knoblauchzehen",
    "garlic paste": "Knoblauchpaste",
    "ginger": "Ingwer",
    "ginger paste": "Ingwerpaste",
    "ginger-garlic paste": "Ingwer-Knoblauch-Paste",
    "gochujang": "Gochujang (koreanische Chilipaste)",
    "green chili": "grüne Chili",
    "green curry paste": "grüne Currypaste",
    "ground beef": "Rinderhack",
    "heavy cream": "Schlagsahne",
    "herbes de provence": "Kräuter der Provence",
    "ice water": "Eiswasser",
    "jalapeno": "Jalapeño",
    "kaffir lime leaves": "Kaffirlimettenblätter",
    "kalamata olives": "Kalamata-Oliven",
    "kashmiri chili powder": "Kashmiri-Chilipulver",
    "kasuri methi": "Kasuri Methi (getrocknete Bockshornkleeblätter)",
    "ketchup": "Ketchup",
    "lemon juice": "Zitronensaft",
    "lettuce leaves": "Kopfsalatblätter",
    "lime juice": "Limettensaft",
    "maple syrup": "Ahornsirup",
    "mirin": "Mirin",
    "miso paste": "Miso-Paste",
    "mustard": "Senf",
    "olive oil": "Olivenöl",
    "onion": "Zwiebel",
    "orange juice": "Orangensaft",
    "palm sugar": "Palmzucker",
    "parmesan cheese": "Parmesan",
    "parsley": "Petersilie",
    "peas": "Erbsen",
    "pickles": "Essiggurken",
    "pineapple": "Ananas",
    "plain yogurt": "Naturjoghurt",
    "potatoes": "Kartoffeln",
    "red chili flakes": "rote Chiliflocken",
    "red onion": "rote Zwiebel",
    "rice": "Reis",
    "ripe avocados": "reife Avocados",
    "roasted peanuts": "geröstete Erdnüsse",
    "sake": "Sake",
    "salt": "Salz",
    "sesame oil": "Sesamöl",
    "sesame seeds": "Sesamsamen",
    "shiitake mushrooms": "Shiitake-Pilze",
    "sichuan peppercorns": "Sichuan-Pfefferkörner",
    "silken tofu": "Seidentofu",
    "soy sauce": "Sojasauce",
    "spaghetti": "Spaghetti",
    "spinach": "Spinat",
    "spring onion": "Frühlingszwiebel",
    "sugar": "Zucker",
    "tahini": "Tahini",
    "thai basil leaves": "Thai-Basilikumblätter",
    "thai eggplant or zucchini": "Thai-Aubergine oder Zucchini",
    "tomato": "Tomate",
    "tomato puree": "Tomatenpüree",
    "tomatoes": "Tomaten",
    "turmeric powder": "Kurkumapulver",
    "vegetable oil": "Pflanzenöl",
    "water": "Wasser",
    "white onion": "weiße Zwiebel",
    "zucchini": "Zucchini",
    "black pepper ": "schwarzer Pfeffer",
}
